[package]
name = "ndarray-benches"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.16.1", features = ["rayon"] }
ndarray-rand = "0.15.0"

anyhow = "1.0.44"
accelerate-src = { version = "0.3.2", optional = true }
intel-mkl-src = { version = "0.8.1", optional = true }
blas-src = { version = "0.10", optional = true }
memmap2 = "0.9.5"
safetensors = "0.4.5"
serde_json = "1.0.128"
serde = { version = "1.0.208", features = ["derive"] }
rayon = "1.10.0"


[dev-dependencies]
criterion = { version = "0.5.1", default-features = false }


[features]
default = []
accelerate = ["dep:accelerate-src", "ndarray/blas"]
blas = ["blas-src/blis","ndarray/blas"]
mkl = ["dep:intel-mkl-src", "blas-src/intel-mkl", "ndarray/blas"]

[[bench]]
name = "benchmarks"
harness = false